### ISSUE TITLE
SLEEP dir usage

### ISSUE THREAD

**Issue by dpaez** [datproject/sdk#20]
Hello y'all, this is a question about hyperdrive, the sdk and the `.dat` folder that we use to find after using the dat CLI `create` or `share` commands. 
From my understanding the `.dat` folder contains [SLEEP](https://github.com/datprotocol/DEPs/blob/master/proposals/0009-sleep-headers.md) related files. The current sdk behavior is to create a `.dat` file containing the public key only. Is this desired behavior? I mean maybe the SLEEP format is not longer used anymore. Or maybe there is a module to handle SLEEP dir creation. I'm playing with `dat-storage` with no luck yet.

My use case involves something similar to `dat-node` but using latest hyperdrive mainly. 

Thanks in advance for any info 👋

**Comment by RangerMauve** [comment]
Hey! The SDK still uses SLEEP, it's just that instead of storing the data inside the `.dat` folder, it stores it in the user folder. The idea there was to have deduplication of data across applications using the SDK, and was adapted from what the hyperdrive daemon was doing.

It uses the [env-paths](https://github.com/sindresorhus/env-paths#pathsdata) module to determine what the proper directory should be per platform rather than polluting the user's home dir with another directory.

Do you need to have finer grained control over where the data is being stored?

**Comment by dpaez** [comment]
Thanks for the quick response and clarification @RangerMauve.
